### ISSUE TITLE
Suche sollte serverseitig arbeiten

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-spider#107]
Aktuell wird eine Liste aller Sites zum Client übertragen, bevor Nutzer mit der Webapp interagieren können. Das dauert inakzeptabel lang.

Wir sollten auf eine serverseitige Such-API auf Basis von ElasticSearch umstellen.

Damit würden erst Daten zum Client übertragen, sobald Nutzer einen Suchbegriff eingeben. Allerdings würden nur die zur suche passenden Treffer übertragen. Die dabei anfallenden Ergebnisgrößen sind in aller Regel nur ein Bruchteil der gesamten Liste. Ausnahmen sind Suchbegriffe wie `gruen` oder `www`, die viele Treffer erzeugen.

EIn weiterer Unterschied wäre, dass wir die Offline-Fähigkeit verlieren. Die hat aber ohnehin keinen hohen Stellenwert.

### Indexierung

- Wir wollen die Daten im Suchindex so aktuell wie möglich halten. Aktuell arbeiten wir mit bis zu 15 Minuten Verzögerung durch Caching.
- Einfache Lösung: periodisch einen Job ausführen, der die neusten Datensätze aus der Ergebnis-Datenbank liest und in den Index schreibt.
- Zusätzlich sollten veraltete Ergebnisse aus dem Index entfernt werden.

### TODO

- [x] ElasticSearch Docker Image auswählen
- [x] ElasticSearch Schema anlegen, Indexierung implementieren
- [x] [API](https://github.com/netzbegruenung/green-spider-api) umschreiben
- [x] Webapp umbauen
- [x] Deployment anpassen

**Comment by DirkR** [comment]
:+1:

**Comment by marians** [comment]
Das ist bis auf Kleinigkeiten soweit umgesetzt und deployed.

**Comment by marians** [comment]
Für den Indexer gibt es diese neue repository: https://github.com/netzbegruenung/green-spider-indexer
