### ISSUE TITLE
Umbau der Webapp

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-spider#76]
## Ziele

Die Webapp soll deutlich benutzer*innenfreundlicher werden! Einige Dinge, die ich gerne erreichen möchte:

- Die Anwendung soll sich schnell laden.
- Jeder soll seine Site schnell und einfach finden und wiederfinden können.
- Die Anwendung soll auch auf dem Smartphone bedienbar sein.
- Prüfkriterien und Empfehlungen für Verbesserungen sollen verständlich und nachvollziehbar sein.

## Entwurf

Hier gibt es einen Prototypen:

https://xd.adobe.com/spec/72ad8c9a-3959-4b13-5ebc-ee351937154e-049c/

Und hier noch mal zur Ansicht:

![image](https://user-images.githubusercontent.com/273727/47178490-ae7ff800-d31b-11e8-9a3b-672aaf0c5034.png)

## TODO

- [ ] Umsetzung einer Navigationsstruktur von Liste (etwa wie `2 Suchergebnis`, aber ohne Suche) zur Detailseite (`3 Website Detailseite`) und zurück 
- [ ] Erstellung der Textinhalte zu den Kriterien (siehe `4 Empfehlung Detailseite`)
- [ ] Verlinkung von `3 Website Detailseite` zu `4 Empfehlung Detailseite`
- [ ] Umbau des Datenexports:
  - Export einer JSON-Datei für die Liste (Startseite) bzw. Suche.
  - Export einer JSON-Datei für jede Site mit allen Details.
- [ ] Suchfunktion und Startseiten-Inhalte
- [ ] Favoriten-Funktion mit Benachrichtigung

**Comment by marians** [comment]
https://github.com/netzbegruenung/green-spider-webapp/pull/11 ist gemerged. Damit ändert sich:

- Die Startseite zeigt nur wenige Details je Site, weitere Details gibt es auf der Detailseite.
- Um das umzusetzen, wird nun [React Router](https://reacttraining.com/react-router/) eingesetzt. Damit die Anwendung auch über beliebige Detailseiten-URLs aufgerufen werden kann, kann die Site nicht mehr über Github Pages gehostet werden. Sie läuft nun, immer noch als statische Site, aber mit entsprechener Server-Konfiguration, auf Hetzner Cloud.
- Screenshots werden direkt auf der Detailseite angezeigt.
- Der Punktestand der Site wird in Bezug zu anderen Sites gesetzt (alle Sites, alle des gleichen Gliederungs-Typs.

**Comment by marians** [comment]
https://github.com/netzbegruenung/green-spider-webapp/pull/13 ist gemerged. Damit verschwindet die vollständige Liste aller Sites von der Startseite und wird durch eine Suche ersetzt.
